spring.application.name=BUPT_Note

#Redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.database=0

#MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/bupt_note

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bupt_note?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mjspxr131019
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=600000



#Spring Security
spring.security.user.name=admin
spring.security.user.password=Mas0n131019


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.data.jpa.repositories.enabled=true

spring.data.mongodb.repositories.enabled=true


# JPA SQL ??

# MongoDB ????
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG